# Generated by Django 2.1.2 on 2019-03-21 21:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='person',
            new_name='userid',
        ),
        migrations.AddField(
            model_name='profile',
            name='uname',
            field=models.CharField(default=django.utils.timezone.now, max_length=60),
            preserve_default=False,
        ),
    ]
